version: "3.8"

services:
  train:
    container_name: ${TRAIN_NAME}-container
    build:
      context: .
      target: base
    image: ${TRAIN_NAME}:latest
    env_file:
      - .env
    volumes:
      - ./dataset:/app/dataset
      - ./logs:/app/logs
      - ./output:/app/output
    command: sh -c "make run.modelling"
    environment:
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY}
      - CLEARML_API_HOST=${CLEARML_API_HOST}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
