experiment_0:
  name: resnet50
  pretrained: true
  freeze_backbone: true
  dropout: 0.5
  hidden_dim: 512
  learning_rate: 1e-3

experiment_1:
  name: resnet50
  pretrained: true
  freeze_backbone: false
  dropout: 0.5
  hidden_dim: 512
  learning_rate: 1e-3

experiment_2:
  name: resnet50
  pretrained: true
  freeze_backbone: false
  dropout: 0.3
  hidden_dim: 1024
  learning_rate: 5e-4

experiment_3:
  name: resnet18
  pretrained: true
  freeze_backbone: false
  dropout: 0.2
  hidden_dim: 128
  learning_rate: 5e-4

experiment_4:
  name: resnet50
  pretrained: true
  freeze_backbone: false
  dropout: 0.2
  hidden_dim: 512
  learning_rate: 5e-4
