defaults:
  - _self_
  - models: models

task: multilabel
num_classes: 17
active_model_index: 0
seed: 12345

dataset:
  img_size:
    - 224
    - 224
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
  batch_size: 64
  data_split:
  - 0.8
  - 0.2
  num_workers: 19
  persistent_workers: false

onnx:
  providers:
    - CPUExecutionProvider
  logit_tolerance: 1e-4
  dummy_batch_size: 10

trainer:
  devices: 1
  min_epochs: 0
  max_epochs: 1
  log_every_n_steps: 50
  deterministic: true
  overfit_batches: 0.0
  logger: true
  enable_progress_bar: true
